- name: epel
  yum: name=epel-release state=present

- name: clean iptables
  command: iptables -F

- name: disable selinux
  selinux: state=disabled

- name: setup extra packages for Go, vagrant, and libvirt
  yum: name={{ item }} state=present
  with_items:
    - screen
    - git
    - gcc
    - gcc-c++
    - golang
    - qemu-kvm
    - libvirt
    - libxslt-devel 
    - libxml2-devel 
    - libvirt-devel 
    - libguestfs-tools-c
    - wget
    - ansible
    - redhat-rpm-config

- name: install vagrant
  command: yum -y install https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.rpm
  
- name: install 0.0.3 fog
  command: vagrant plugin install --plugin-version 0.0.3 fog-libvirt

- name: install vagrant-libvirt
  shell: vagrant plugin install vagrant-libvirt creates=/root/.vagrant.d/plugins.json

- name: install 0.0.3 fog
  command: vagrant plugin install --plugin-version 0.0.3 fog-libvirt

- name: enable nfs server
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server
